// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/boards.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "BOARDS";

/** message */
export interface Board {
  id: string;
  userId: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateBoardRequest {
  userId: string;
  name: string;
  private: boolean;
}

export interface GetBoardRequest {
  id: string;
}

export interface DeleteBoardRequest {
  id: string;
}

export interface EditeBoardRequest {
  boardId: string;
  boardCover?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  private?: boolean | undefined;
}

export interface MergeBoardRequest {
  mainBoardId: string;
  nestBoardId: string;
}

export interface SuccessMessageResponse {
  success: boolean;
}

export interface ListBoardsRequest {
  cursor?: string | undefined;
  limit: number;
}

export interface ListBoardsResponse {
  boards: Board[];
  pageInfo: ListBoardsResponse_PageInfo | undefined;
}

export interface ListBoardsResponse_PageInfo {
  nextCursor: string;
  limit: number;
}

export const BOARDS_PACKAGE_NAME = "BOARDS";

function createBaseBoard(): Board {
  return { id: "", userId: "", name: "", createdAt: "", updatedAt: "" };
}

export const Board: MessageFns<Board> = {
  encode(message: Board, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(42).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Board {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBoard();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateBoardRequest(): CreateBoardRequest {
  return { userId: "", name: "", private: false };
}

export const CreateBoardRequest: MessageFns<CreateBoardRequest> = {
  encode(message: CreateBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.private !== false) {
      writer.uint32(24).bool(message.private);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.private = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetBoardRequest(): GetBoardRequest {
  return { id: "" };
}

export const GetBoardRequest: MessageFns<GetBoardRequest> = {
  encode(message: GetBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteBoardRequest(): DeleteBoardRequest {
  return { id: "" };
}

export const DeleteBoardRequest: MessageFns<DeleteBoardRequest> = {
  encode(message: DeleteBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseEditeBoardRequest(): EditeBoardRequest {
  return { boardId: "" };
}

export const EditeBoardRequest: MessageFns<EditeBoardRequest> = {
  encode(message: EditeBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.boardId !== "") {
      writer.uint32(10).string(message.boardId);
    }
    if (message.boardCover !== undefined) {
      writer.uint32(18).string(message.boardCover);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.description !== undefined) {
      writer.uint32(34).string(message.description);
    }
    if (message.private !== undefined) {
      writer.uint32(40).bool(message.private);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EditeBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEditeBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.boardId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.boardCover = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.private = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseMergeBoardRequest(): MergeBoardRequest {
  return { mainBoardId: "", nestBoardId: "" };
}

export const MergeBoardRequest: MessageFns<MergeBoardRequest> = {
  encode(message: MergeBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.mainBoardId !== "") {
      writer.uint32(10).string(message.mainBoardId);
    }
    if (message.nestBoardId !== "") {
      writer.uint32(18).string(message.nestBoardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MergeBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMergeBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.mainBoardId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nestBoardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSuccessMessageResponse(): SuccessMessageResponse {
  return { success: false };
}

export const SuccessMessageResponse: MessageFns<SuccessMessageResponse> = {
  encode(message: SuccessMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuccessMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSuccessMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListBoardsRequest(): ListBoardsRequest {
  return { limit: 0 };
}

export const ListBoardsRequest: MessageFns<ListBoardsRequest> = {
  encode(message: ListBoardsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cursor !== undefined) {
      writer.uint32(10).string(message.cursor);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBoardsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBoardsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListBoardsResponse(): ListBoardsResponse {
  return { boards: [], pageInfo: undefined };
}

export const ListBoardsResponse: MessageFns<ListBoardsResponse> = {
  encode(message: ListBoardsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.boards) {
      Board.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pageInfo !== undefined) {
      ListBoardsResponse_PageInfo.encode(message.pageInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBoardsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBoardsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.boards.push(Board.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pageInfo = ListBoardsResponse_PageInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListBoardsResponse_PageInfo(): ListBoardsResponse_PageInfo {
  return { nextCursor: "", limit: 0 };
}

export const ListBoardsResponse_PageInfo: MessageFns<ListBoardsResponse_PageInfo> = {
  encode(message: ListBoardsResponse_PageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nextCursor !== "") {
      writer.uint32(10).string(message.nextCursor);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListBoardsResponse_PageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListBoardsResponse_PageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface BoardsClient {
  createBoard(request: CreateBoardRequest): Observable<Board>;

  deleteBoard(request: DeleteBoardRequest): Observable<SuccessMessageResponse>;

  getBoard(request: GetBoardRequest): Observable<Board>;

  editeBoard(request: EditeBoardRequest): Observable<Board>;

  mergeBoard(request: MergeBoardRequest): Observable<Board>;

  listBoards(request: ListBoardsRequest): Observable<ListBoardsResponse>;
}

export interface BoardsController {
  createBoard(request: CreateBoardRequest): Promise<Board> | Observable<Board> | Board;

  deleteBoard(
    request: DeleteBoardRequest,
  ): Promise<SuccessMessageResponse> | Observable<SuccessMessageResponse> | SuccessMessageResponse;

  getBoard(request: GetBoardRequest): Promise<Board> | Observable<Board> | Board;

  editeBoard(request: EditeBoardRequest): Promise<Board> | Observable<Board> | Board;

  mergeBoard(request: MergeBoardRequest): Promise<Board> | Observable<Board> | Board;

  listBoards(
    request: ListBoardsRequest,
  ): Promise<ListBoardsResponse> | Observable<ListBoardsResponse> | ListBoardsResponse;
}

export function BoardsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createBoard", "deleteBoard", "getBoard", "editeBoard", "mergeBoard", "listBoards"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Boards", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Boards", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BOARDS_SERVICE_NAME = "Boards";

export type BoardsService = typeof BoardsService;
export const BoardsService = {
  createBoard: {
    path: "/BOARDS.Boards/CreateBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateBoardRequest): Buffer => Buffer.from(CreateBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateBoardRequest => CreateBoardRequest.decode(value),
    responseSerialize: (value: Board): Buffer => Buffer.from(Board.encode(value).finish()),
    responseDeserialize: (value: Buffer): Board => Board.decode(value),
  },
  deleteBoard: {
    path: "/BOARDS.Boards/DeleteBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteBoardRequest): Buffer => Buffer.from(DeleteBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteBoardRequest => DeleteBoardRequest.decode(value),
    responseSerialize: (value: SuccessMessageResponse): Buffer =>
      Buffer.from(SuccessMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessMessageResponse => SuccessMessageResponse.decode(value),
  },
  getBoard: {
    path: "/BOARDS.Boards/GetBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetBoardRequest): Buffer => Buffer.from(GetBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetBoardRequest => GetBoardRequest.decode(value),
    responseSerialize: (value: Board): Buffer => Buffer.from(Board.encode(value).finish()),
    responseDeserialize: (value: Buffer): Board => Board.decode(value),
  },
  editeBoard: {
    path: "/BOARDS.Boards/EditeBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: EditeBoardRequest): Buffer => Buffer.from(EditeBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): EditeBoardRequest => EditeBoardRequest.decode(value),
    responseSerialize: (value: Board): Buffer => Buffer.from(Board.encode(value).finish()),
    responseDeserialize: (value: Buffer): Board => Board.decode(value),
  },
  mergeBoard: {
    path: "/BOARDS.Boards/MergeBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: MergeBoardRequest): Buffer => Buffer.from(MergeBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MergeBoardRequest => MergeBoardRequest.decode(value),
    responseSerialize: (value: Board): Buffer => Buffer.from(Board.encode(value).finish()),
    responseDeserialize: (value: Buffer): Board => Board.decode(value),
  },
  listBoards: {
    path: "/BOARDS.Boards/ListBoards" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListBoardsRequest): Buffer => Buffer.from(ListBoardsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListBoardsRequest => ListBoardsRequest.decode(value),
    responseSerialize: (value: ListBoardsResponse): Buffer => Buffer.from(ListBoardsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListBoardsResponse => ListBoardsResponse.decode(value),
  },
} as const;

export interface BoardsServer extends UntypedServiceImplementation {
  createBoard: handleUnaryCall<CreateBoardRequest, Board>;
  deleteBoard: handleUnaryCall<DeleteBoardRequest, SuccessMessageResponse>;
  getBoard: handleUnaryCall<GetBoardRequest, Board>;
  editeBoard: handleUnaryCall<EditeBoardRequest, Board>;
  mergeBoard: handleUnaryCall<MergeBoardRequest, Board>;
  listBoards: handleUnaryCall<ListBoardsRequest, ListBoardsResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
