// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/comments.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "interactions";

export interface Comment {
  id: string;
  userId: string;
  pinId: string;
  text: string;
  createdAt: Timestamp | undefined;
}

export interface AddCommentRequest {
  userId: string;
  pinId: string;
  text: string;
}

export interface AddCommentResponse {
  comment: Comment | undefined;
}

export interface GetCommentsRequest {
  pinId: string;
  cursor: number;
  limit: number;
}

export interface GetCommentsResponse {
  comments: Comment[];
}

export const INTERACTIONS_PACKAGE_NAME = "interactions";

function createBaseComment(): Comment {
  return { id: "", userId: "", pinId: "", text: "", createdAt: undefined };
}

export const Comment: MessageFns<Comment> = {
  encode(message: Comment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(26).string(message.pinId);
    }
    if (message.text !== "") {
      writer.uint32(34).string(message.text);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Comment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddCommentRequest(): AddCommentRequest {
  return { userId: "", pinId: "", text: "" };
}

export const AddCommentRequest: MessageFns<AddCommentRequest> = {
  encode(message: AddCommentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    if (message.text !== "") {
      writer.uint32(26).string(message.text);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCommentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCommentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.text = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddCommentResponse(): AddCommentResponse {
  return { comment: undefined };
}

export const AddCommentResponse: MessageFns<AddCommentResponse> = {
  encode(message: AddCommentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.comment !== undefined) {
      Comment.encode(message.comment, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddCommentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddCommentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.comment = Comment.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetCommentsRequest(): GetCommentsRequest {
  return { pinId: "", cursor: 0, limit: 0 };
}

export const GetCommentsRequest: MessageFns<GetCommentsRequest> = {
  encode(message: GetCommentsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pinId !== "") {
      writer.uint32(10).string(message.pinId);
    }
    if (message.cursor !== 0) {
      writer.uint32(16).int32(message.cursor);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCommentsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCommentsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cursor = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetCommentsResponse(): GetCommentsResponse {
  return { comments: [] };
}

export const GetCommentsResponse: MessageFns<GetCommentsResponse> = {
  encode(message: GetCommentsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.comments) {
      Comment.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCommentsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCommentsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.comments.push(Comment.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface CommentsServiceClient {
  addComment(request: AddCommentRequest): Observable<AddCommentResponse>;

  getComments(request: GetCommentsRequest): Observable<GetCommentsResponse>;
}

export interface CommentsServiceController {
  addComment(
    request: AddCommentRequest,
  ): Promise<AddCommentResponse> | Observable<AddCommentResponse> | AddCommentResponse;

  getComments(
    request: GetCommentsRequest,
  ): Promise<GetCommentsResponse> | Observable<GetCommentsResponse> | GetCommentsResponse;
}

export function CommentsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addComment", "getComments"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CommentsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CommentsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMMENTS_SERVICE_NAME = "CommentsService";

export type CommentsServiceService = typeof CommentsServiceService;
export const CommentsServiceService = {
  addComment: {
    path: "/interactions.CommentsService/AddComment" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddCommentRequest): Buffer => Buffer.from(AddCommentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddCommentRequest => AddCommentRequest.decode(value),
    responseSerialize: (value: AddCommentResponse): Buffer => Buffer.from(AddCommentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddCommentResponse => AddCommentResponse.decode(value),
  },
  getComments: {
    path: "/interactions.CommentsService/GetComments" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetCommentsRequest): Buffer => Buffer.from(GetCommentsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetCommentsRequest => GetCommentsRequest.decode(value),
    responseSerialize: (value: GetCommentsResponse): Buffer => Buffer.from(GetCommentsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetCommentsResponse => GetCommentsResponse.decode(value),
  },
} as const;

export interface CommentsServiceServer extends UntypedServiceImplementation {
  addComment: handleUnaryCall<AddCommentRequest, AddCommentResponse>;
  getComments: handleUnaryCall<GetCommentsRequest, GetCommentsResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
