// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/feed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "feed";

/** message */
export interface FeedItem {
  id: string;
  type: string;
  userId: string;
  targetId: string;
  title: string;
  description: string;
  url: string;
  tags: string[];
  interests: string[];
  createdAt: Timestamp | undefined;
}

export interface GetFeedRequest {
  userId: string;
  cursor: number;
  limit: number;
}

export interface GetFeedResponse {
  items: FeedItem[];
  nextCursor: number;
}

export const FEED_PACKAGE_NAME = "feed";

function createBaseFeedItem(): FeedItem {
  return {
    id: "",
    type: "",
    userId: "",
    targetId: "",
    title: "",
    description: "",
    url: "",
    tags: [],
    interests: [],
    createdAt: undefined,
  };
}

export const FeedItem: MessageFns<FeedItem> = {
  encode(message: FeedItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.targetId !== "") {
      writer.uint32(34).string(message.targetId);
    }
    if (message.title !== "") {
      writer.uint32(42).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(50).string(message.description);
    }
    if (message.url !== "") {
      writer.uint32(58).string(message.url);
    }
    for (const v of message.tags) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.interests) {
      writer.uint32(74).string(v!);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.targetId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.interests.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetFeedRequest(): GetFeedRequest {
  return { userId: "", cursor: 0, limit: 0 };
}

export const GetFeedRequest: MessageFns<GetFeedRequest> = {
  encode(message: GetFeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.cursor !== 0) {
      writer.uint32(16).int32(message.cursor);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.cursor = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetFeedResponse(): GetFeedResponse {
  return { items: [], nextCursor: 0 };
}

export const GetFeedResponse: MessageFns<GetFeedResponse> = {
  encode(message: GetFeedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.items) {
      FeedItem.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.nextCursor !== 0) {
      writer.uint32(16).int32(message.nextCursor);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFeedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFeedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.items.push(FeedItem.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.nextCursor = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** Feed Service */

export interface FeedServiceClient {
  getFeed(request: GetFeedRequest): Observable<GetFeedResponse>;
}

/** Feed Service */

export interface FeedServiceController {
  getFeed(request: GetFeedRequest): Promise<GetFeedResponse> | Observable<GetFeedResponse> | GetFeedResponse;
}

export function FeedServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getFeed"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FeedService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FeedService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FEED_SERVICE_NAME = "FeedService";

/** Feed Service */
export type FeedServiceService = typeof FeedServiceService;
export const FeedServiceService = {
  getFeed: {
    path: "/feed.FeedService/GetFeed" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetFeedRequest): Buffer => Buffer.from(GetFeedRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetFeedRequest => GetFeedRequest.decode(value),
    responseSerialize: (value: GetFeedResponse): Buffer => Buffer.from(GetFeedResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetFeedResponse => GetFeedResponse.decode(value),
  },
} as const;

export interface FeedServiceServer extends UntypedServiceImplementation {
  getFeed: handleUnaryCall<GetFeedRequest, GetFeedResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
