// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/Interests.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "interactions";

export interface Interest {
  id: string;
  name: string;
}

export interface UserInterest {
  userId: string;
  interestId: string;
  createdAt: Timestamp | undefined;
}

export interface PinInterest {
  pinId: string;
  interestId: string;
  createdAt: Timestamp | undefined;
}

export interface AddUserInterestRequest {
  userId: string;
  interestId: string;
}

export interface AddUserInterestResponse {
  userInterest: UserInterest | undefined;
}

export interface AddPinInterestRequest {
  pinId: string;
  interestId: string;
}

export interface AddPinInterestResponse {
  pinInterest: PinInterest | undefined;
}

export const INTERACTIONS_PACKAGE_NAME = "interactions";

function createBaseInterest(): Interest {
  return { id: "", name: "" };
}

export const Interest: MessageFns<Interest> = {
  encode(message: Interest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Interest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInterest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUserInterest(): UserInterest {
  return { userId: "", interestId: "", createdAt: undefined };
}

export const UserInterest: MessageFns<UserInterest> = {
  encode(message: UserInterest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.interestId !== "") {
      writer.uint32(18).string(message.interestId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserInterest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserInterest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.interestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBasePinInterest(): PinInterest {
  return { pinId: "", interestId: "", createdAt: undefined };
}

export const PinInterest: MessageFns<PinInterest> = {
  encode(message: PinInterest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pinId !== "") {
      writer.uint32(10).string(message.pinId);
    }
    if (message.interestId !== "") {
      writer.uint32(18).string(message.interestId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(message.createdAt, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PinInterest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePinInterest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.interestId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddUserInterestRequest(): AddUserInterestRequest {
  return { userId: "", interestId: "" };
}

export const AddUserInterestRequest: MessageFns<AddUserInterestRequest> = {
  encode(message: AddUserInterestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.interestId !== "") {
      writer.uint32(18).string(message.interestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddUserInterestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddUserInterestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.interestId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddUserInterestResponse(): AddUserInterestResponse {
  return { userInterest: undefined };
}

export const AddUserInterestResponse: MessageFns<AddUserInterestResponse> = {
  encode(message: AddUserInterestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userInterest !== undefined) {
      UserInterest.encode(message.userInterest, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddUserInterestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddUserInterestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userInterest = UserInterest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddPinInterestRequest(): AddPinInterestRequest {
  return { pinId: "", interestId: "" };
}

export const AddPinInterestRequest: MessageFns<AddPinInterestRequest> = {
  encode(message: AddPinInterestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pinId !== "") {
      writer.uint32(10).string(message.pinId);
    }
    if (message.interestId !== "") {
      writer.uint32(18).string(message.interestId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPinInterestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPinInterestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.interestId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddPinInterestResponse(): AddPinInterestResponse {
  return { pinInterest: undefined };
}

export const AddPinInterestResponse: MessageFns<AddPinInterestResponse> = {
  encode(message: AddPinInterestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pinInterest !== undefined) {
      PinInterest.encode(message.pinInterest, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPinInterestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPinInterestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pinInterest = PinInterest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface InterestsServiceClient {
  addUserInterest(request: AddUserInterestRequest): Observable<AddUserInterestResponse>;

  addPinInterest(request: AddPinInterestRequest): Observable<AddPinInterestResponse>;
}

export interface InterestsServiceController {
  addUserInterest(
    request: AddUserInterestRequest,
  ): Promise<AddUserInterestResponse> | Observable<AddUserInterestResponse> | AddUserInterestResponse;

  addPinInterest(
    request: AddPinInterestRequest,
  ): Promise<AddPinInterestResponse> | Observable<AddPinInterestResponse> | AddPinInterestResponse;
}

export function InterestsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addUserInterest", "addPinInterest"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InterestsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InterestsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INTERESTS_SERVICE_NAME = "InterestsService";

export type InterestsServiceService = typeof InterestsServiceService;
export const InterestsServiceService = {
  addUserInterest: {
    path: "/interactions.InterestsService/AddUserInterest" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddUserInterestRequest): Buffer =>
      Buffer.from(AddUserInterestRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddUserInterestRequest => AddUserInterestRequest.decode(value),
    responseSerialize: (value: AddUserInterestResponse): Buffer =>
      Buffer.from(AddUserInterestResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddUserInterestResponse => AddUserInterestResponse.decode(value),
  },
  addPinInterest: {
    path: "/interactions.InterestsService/AddPinInterest" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddPinInterestRequest): Buffer =>
      Buffer.from(AddPinInterestRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddPinInterestRequest => AddPinInterestRequest.decode(value),
    responseSerialize: (value: AddPinInterestResponse): Buffer =>
      Buffer.from(AddPinInterestResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AddPinInterestResponse => AddPinInterestResponse.decode(value),
  },
} as const;

export interface InterestsServiceServer extends UntypedServiceImplementation {
  addUserInterest: handleUnaryCall<AddUserInterestRequest, AddUserInterestResponse>;
  addPinInterest: handleUnaryCall<AddPinInterestRequest, AddPinInterestResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
