// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/likes.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "interactions";

/** Like على Pin */
export interface Like {
  userId: string;
  pinId: string;
  createdAt: string;
}

export interface AddLikeRequest {
  userId: string;
  pinId: string;
}

export interface RemoveLikeRequest {
  userId: string;
  pinId: string;
}

export interface RemoveLikeResponse {
  success: boolean;
}

export const INTERACTIONS_PACKAGE_NAME = "interactions";

function createBaseLike(): Like {
  return { userId: "", pinId: "", createdAt: "" };
}

export const Like: MessageFns<Like> = {
  encode(message: Like, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    if (message.createdAt !== "") {
      writer.uint32(26).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Like {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLike();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddLikeRequest(): AddLikeRequest {
  return { userId: "", pinId: "" };
}

export const AddLikeRequest: MessageFns<AddLikeRequest> = {
  encode(message: AddLikeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddLikeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddLikeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveLikeRequest(): RemoveLikeRequest {
  return { userId: "", pinId: "" };
}

export const RemoveLikeRequest: MessageFns<RemoveLikeRequest> = {
  encode(message: RemoveLikeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveLikeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveLikeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveLikeResponse(): RemoveLikeResponse {
  return { success: false };
}

export const RemoveLikeResponse: MessageFns<RemoveLikeResponse> = {
  encode(message: RemoveLikeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveLikeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveLikeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface LikesClient {
  addLike(request: AddLikeRequest): Observable<Like>;

  removeLike(request: RemoveLikeRequest): Observable<RemoveLikeResponse>;
}

export interface LikesController {
  addLike(request: AddLikeRequest): Promise<Like> | Observable<Like> | Like;

  removeLike(
    request: RemoveLikeRequest,
  ): Promise<RemoveLikeResponse> | Observable<RemoveLikeResponse> | RemoveLikeResponse;
}

export function LikesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addLike", "removeLike"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Likes", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Likes", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const LIKES_SERVICE_NAME = "Likes";

export type LikesService = typeof LikesService;
export const LikesService = {
  addLike: {
    path: "/interactions.Likes/AddLike" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddLikeRequest): Buffer => Buffer.from(AddLikeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddLikeRequest => AddLikeRequest.decode(value),
    responseSerialize: (value: Like): Buffer => Buffer.from(Like.encode(value).finish()),
    responseDeserialize: (value: Buffer): Like => Like.decode(value),
  },
  removeLike: {
    path: "/interactions.Likes/RemoveLike" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RemoveLikeRequest): Buffer => Buffer.from(RemoveLikeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RemoveLikeRequest => RemoveLikeRequest.decode(value),
    responseSerialize: (value: RemoveLikeResponse): Buffer => Buffer.from(RemoveLikeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RemoveLikeResponse => RemoveLikeResponse.decode(value),
  },
} as const;

export interface LikesServer extends UntypedServiceImplementation {
  addLike: handleUnaryCall<AddLikeRequest, Like>;
  removeLike: handleUnaryCall<RemoveLikeRequest, RemoveLikeResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
