// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/pins.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "PINS";

export enum PinType {
  IMAGE = 0,
  VIDEO = 1,
  UNRECOGNIZED = -1,
}

export interface Pin {
  id: string;
  userId: string;
  title: string;
  description: string;
  link: string;
  width: number;
  height: number;
  type: PinType;
  url: string;
  publicId: string;
  allowComments: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePinRequest {
  userId: string;
  title: string;
  description: string;
  link: string;
  width: number;
  height: number;
  type: PinType;
  url: string;
  publicId: string;
  allowComments: boolean;
}

export interface GetPinRequest {
  id: string;
}

export interface DeletePinRequest {
  id: string;
}

export interface SuccessMessageResponse {
  success: boolean;
}

export interface ListPinsRequest {
  cursor: string;
  limit: number;
}

export interface ListPinsResponse {
  pins: Pin[];
  pageInfo: ListPinsResponse_PageInfo | undefined;
}

export interface ListPinsResponse_PageInfo {
  nextCursor: string;
  hasNext: boolean;
}

export const PINS_PACKAGE_NAME = "PINS";

function createBasePin(): Pin {
  return {
    id: "",
    userId: "",
    title: "",
    description: "",
    link: "",
    width: 0,
    height: 0,
    type: 0,
    url: "",
    publicId: "",
    allowComments: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const Pin: MessageFns<Pin> = {
  encode(message: Pin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.link !== "") {
      writer.uint32(42).string(message.link);
    }
    if (message.width !== 0) {
      writer.uint32(48).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(56).int32(message.height);
    }
    if (message.type !== 0) {
      writer.uint32(64).int32(message.type);
    }
    if (message.url !== "") {
      writer.uint32(74).string(message.url);
    }
    if (message.publicId !== "") {
      writer.uint32(82).string(message.publicId);
    }
    if (message.allowComments !== false) {
      writer.uint32(88).bool(message.allowComments);
    }
    if (message.createdAt !== "") {
      writer.uint32(98).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(106).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Pin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.link = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.publicId = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.allowComments = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreatePinRequest(): CreatePinRequest {
  return {
    userId: "",
    title: "",
    description: "",
    link: "",
    width: 0,
    height: 0,
    type: 0,
    url: "",
    publicId: "",
    allowComments: false,
  };
}

export const CreatePinRequest: MessageFns<CreatePinRequest> = {
  encode(message: CreatePinRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.link !== "") {
      writer.uint32(34).string(message.link);
    }
    if (message.width !== 0) {
      writer.uint32(40).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(48).int32(message.height);
    }
    if (message.type !== 0) {
      writer.uint32(56).int32(message.type);
    }
    if (message.url !== "") {
      writer.uint32(66).string(message.url);
    }
    if (message.publicId !== "") {
      writer.uint32(74).string(message.publicId);
    }
    if (message.allowComments !== false) {
      writer.uint32(80).bool(message.allowComments);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreatePinRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreatePinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.link = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.publicId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.allowComments = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetPinRequest(): GetPinRequest {
  return { id: "" };
}

export const GetPinRequest: MessageFns<GetPinRequest> = {
  encode(message: GetPinRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPinRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeletePinRequest(): DeletePinRequest {
  return { id: "" };
}

export const DeletePinRequest: MessageFns<DeletePinRequest> = {
  encode(message: DeletePinRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeletePinRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeletePinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseSuccessMessageResponse(): SuccessMessageResponse {
  return { success: false };
}

export const SuccessMessageResponse: MessageFns<SuccessMessageResponse> = {
  encode(message: SuccessMessageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SuccessMessageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSuccessMessageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPinsRequest(): ListPinsRequest {
  return { cursor: "", limit: 0 };
}

export const ListPinsRequest: MessageFns<ListPinsRequest> = {
  encode(message: ListPinsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.cursor !== "") {
      writer.uint32(10).string(message.cursor);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPinsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPinsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPinsResponse(): ListPinsResponse {
  return { pins: [], pageInfo: undefined };
}

export const ListPinsResponse: MessageFns<ListPinsResponse> = {
  encode(message: ListPinsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.pins) {
      Pin.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.pageInfo !== undefined) {
      ListPinsResponse_PageInfo.encode(message.pageInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPinsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPinsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pins.push(Pin.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pageInfo = ListPinsResponse_PageInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseListPinsResponse_PageInfo(): ListPinsResponse_PageInfo {
  return { nextCursor: "", hasNext: false };
}

export const ListPinsResponse_PageInfo: MessageFns<ListPinsResponse_PageInfo> = {
  encode(message: ListPinsResponse_PageInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nextCursor !== "") {
      writer.uint32(10).string(message.nextCursor);
    }
    if (message.hasNext !== false) {
      writer.uint32(16).bool(message.hasNext);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPinsResponse_PageInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPinsResponse_PageInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasNext = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

/** Service */

export interface PinsClient {
  createPin(request: CreatePinRequest): Observable<Pin>;

  publishPin(request: CreatePinRequest): Observable<SuccessMessageResponse>;

  deletePin(request: DeletePinRequest): Observable<SuccessMessageResponse>;

  getPin(request: GetPinRequest): Observable<Pin>;

  listPins(request: ListPinsRequest): Observable<ListPinsResponse>;
}

/** Service */

export interface PinsController {
  createPin(request: CreatePinRequest): Promise<Pin> | Observable<Pin> | Pin;

  publishPin(
    request: CreatePinRequest,
  ): Promise<SuccessMessageResponse> | Observable<SuccessMessageResponse> | SuccessMessageResponse;

  deletePin(
    request: DeletePinRequest,
  ): Promise<SuccessMessageResponse> | Observable<SuccessMessageResponse> | SuccessMessageResponse;

  getPin(request: GetPinRequest): Promise<Pin> | Observable<Pin> | Pin;

  listPins(request: ListPinsRequest): Promise<ListPinsResponse> | Observable<ListPinsResponse> | ListPinsResponse;
}

export function PinsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createPin", "publishPin", "deletePin", "getPin", "listPins"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Pins", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Pins", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PINS_SERVICE_NAME = "Pins";

/** Service */
export type PinsService = typeof PinsService;
export const PinsService = {
  createPin: {
    path: "/PINS.Pins/CreatePin" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreatePinRequest): Buffer => Buffer.from(CreatePinRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreatePinRequest => CreatePinRequest.decode(value),
    responseSerialize: (value: Pin): Buffer => Buffer.from(Pin.encode(value).finish()),
    responseDeserialize: (value: Buffer): Pin => Pin.decode(value),
  },
  publishPin: {
    path: "/PINS.Pins/PublishPin" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreatePinRequest): Buffer => Buffer.from(CreatePinRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreatePinRequest => CreatePinRequest.decode(value),
    responseSerialize: (value: SuccessMessageResponse): Buffer =>
      Buffer.from(SuccessMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessMessageResponse => SuccessMessageResponse.decode(value),
  },
  deletePin: {
    path: "/PINS.Pins/DeletePin" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeletePinRequest): Buffer => Buffer.from(DeletePinRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeletePinRequest => DeletePinRequest.decode(value),
    responseSerialize: (value: SuccessMessageResponse): Buffer =>
      Buffer.from(SuccessMessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): SuccessMessageResponse => SuccessMessageResponse.decode(value),
  },
  getPin: {
    path: "/PINS.Pins/GetPin" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetPinRequest): Buffer => Buffer.from(GetPinRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPinRequest => GetPinRequest.decode(value),
    responseSerialize: (value: Pin): Buffer => Buffer.from(Pin.encode(value).finish()),
    responseDeserialize: (value: Buffer): Pin => Pin.decode(value),
  },
  listPins: {
    path: "/PINS.Pins/ListPins" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListPinsRequest): Buffer => Buffer.from(ListPinsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListPinsRequest => ListPinsRequest.decode(value),
    responseSerialize: (value: ListPinsResponse): Buffer => Buffer.from(ListPinsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListPinsResponse => ListPinsResponse.decode(value),
  },
} as const;

export interface PinsServer extends UntypedServiceImplementation {
  createPin: handleUnaryCall<CreatePinRequest, Pin>;
  publishPin: handleUnaryCall<CreatePinRequest, SuccessMessageResponse>;
  deletePin: handleUnaryCall<DeletePinRequest, SuccessMessageResponse>;
  getPin: handleUnaryCall<GetPinRequest, Pin>;
  listPins: handleUnaryCall<ListPinsRequest, ListPinsResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
