// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v7.34.0
// source: proto/saves.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "SAVES";

export interface Save {
  id: string;
  userId: string;
  pinId: string;
  createdAt: string;
}

export interface AddSaveRequest {
  userId: string;
  pinId: string;
  boardId?: string | undefined;
}

export interface RemoveSaveRequest {
  userId: string;
  pinId: string;
  boardId?: string | undefined;
}

/** رد إزالة save */
export interface RemoveSaveResponse {
  success: boolean;
}

/** طلب جلب كل الـ saves لمستخدم */
export interface GetSavesByBoardRequest {
  userId: string;
}

export interface GetUnorganizedSavesRequest {
  userId: string;
}

export interface GetSavesResponse {
  saves: Save[];
}

/** طلب التحقق من save */
export interface CheckSaveRequest {
  userId: string;
  pinId: string;
}

export interface CheckSaveResponse {
  saved: boolean;
}

export const SAVES_PACKAGE_NAME = "SAVES";

function createBaseSave(): Save {
  return { id: "", userId: "", pinId: "", createdAt: "" };
}

export const Save: MessageFns<Save> = {
  encode(message: Save, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.userId !== "") {
      writer.uint32(18).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(26).string(message.pinId);
    }
    if (message.createdAt !== "") {
      writer.uint32(34).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Save {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSave();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseAddSaveRequest(): AddSaveRequest {
  return { userId: "", pinId: "" };
}

export const AddSaveRequest: MessageFns<AddSaveRequest> = {
  encode(message: AddSaveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    if (message.boardId !== undefined) {
      writer.uint32(26).string(message.boardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddSaveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddSaveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.boardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveSaveRequest(): RemoveSaveRequest {
  return { userId: "", pinId: "" };
}

export const RemoveSaveRequest: MessageFns<RemoveSaveRequest> = {
  encode(message: RemoveSaveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    if (message.boardId !== undefined) {
      writer.uint32(26).string(message.boardId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveSaveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveSaveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.boardId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseRemoveSaveResponse(): RemoveSaveResponse {
  return { success: false };
}

export const RemoveSaveResponse: MessageFns<RemoveSaveResponse> = {
  encode(message: RemoveSaveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RemoveSaveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRemoveSaveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetSavesByBoardRequest(): GetSavesByBoardRequest {
  return { userId: "" };
}

export const GetSavesByBoardRequest: MessageFns<GetSavesByBoardRequest> = {
  encode(message: GetSavesByBoardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSavesByBoardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSavesByBoardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUnorganizedSavesRequest(): GetUnorganizedSavesRequest {
  return { userId: "" };
}

export const GetUnorganizedSavesRequest: MessageFns<GetUnorganizedSavesRequest> = {
  encode(message: GetUnorganizedSavesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUnorganizedSavesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUnorganizedSavesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetSavesResponse(): GetSavesResponse {
  return { saves: [] };
}

export const GetSavesResponse: MessageFns<GetSavesResponse> = {
  encode(message: GetSavesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.saves) {
      Save.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSavesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSavesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.saves.push(Save.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckSaveRequest(): CheckSaveRequest {
  return { userId: "", pinId: "" };
}

export const CheckSaveRequest: MessageFns<CheckSaveRequest> = {
  encode(message: CheckSaveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.pinId !== "") {
      writer.uint32(18).string(message.pinId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckSaveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSaveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pinId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCheckSaveResponse(): CheckSaveResponse {
  return { saved: false };
}

export const CheckSaveResponse: MessageFns<CheckSaveResponse> = {
  encode(message: CheckSaveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.saved !== false) {
      writer.uint32(8).bool(message.saved);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckSaveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckSaveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.saved = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface SavesClient {
  addSave(request: AddSaveRequest): Observable<Save>;

  removeSave(request: RemoveSaveRequest): Observable<RemoveSaveResponse>;

  getSavesByBoard(request: GetSavesByBoardRequest): Observable<GetSavesResponse>;

  getUnorganizedSaves(request: GetUnorganizedSavesRequest): Observable<GetSavesResponse>;

  checkSave(request: CheckSaveRequest): Observable<CheckSaveResponse>;
}

export interface SavesController {
  addSave(request: AddSaveRequest): Promise<Save> | Observable<Save> | Save;

  removeSave(
    request: RemoveSaveRequest,
  ): Promise<RemoveSaveResponse> | Observable<RemoveSaveResponse> | RemoveSaveResponse;

  getSavesByBoard(
    request: GetSavesByBoardRequest,
  ): Promise<GetSavesResponse> | Observable<GetSavesResponse> | GetSavesResponse;

  getUnorganizedSaves(
    request: GetUnorganizedSavesRequest,
  ): Promise<GetSavesResponse> | Observable<GetSavesResponse> | GetSavesResponse;

  checkSave(request: CheckSaveRequest): Promise<CheckSaveResponse> | Observable<CheckSaveResponse> | CheckSaveResponse;
}

export function SavesControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["addSave", "removeSave", "getSavesByBoard", "getUnorganizedSaves", "checkSave"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Saves", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Saves", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SAVES_SERVICE_NAME = "Saves";

export type SavesService = typeof SavesService;
export const SavesService = {
  addSave: {
    path: "/SAVES.Saves/AddSave" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AddSaveRequest): Buffer => Buffer.from(AddSaveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AddSaveRequest => AddSaveRequest.decode(value),
    responseSerialize: (value: Save): Buffer => Buffer.from(Save.encode(value).finish()),
    responseDeserialize: (value: Buffer): Save => Save.decode(value),
  },
  removeSave: {
    path: "/SAVES.Saves/RemoveSave" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: RemoveSaveRequest): Buffer => Buffer.from(RemoveSaveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RemoveSaveRequest => RemoveSaveRequest.decode(value),
    responseSerialize: (value: RemoveSaveResponse): Buffer => Buffer.from(RemoveSaveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RemoveSaveResponse => RemoveSaveResponse.decode(value),
  },
  getSavesByBoard: {
    path: "/SAVES.Saves/GetSavesByBoard" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetSavesByBoardRequest): Buffer =>
      Buffer.from(GetSavesByBoardRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetSavesByBoardRequest => GetSavesByBoardRequest.decode(value),
    responseSerialize: (value: GetSavesResponse): Buffer => Buffer.from(GetSavesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSavesResponse => GetSavesResponse.decode(value),
  },
  getUnorganizedSaves: {
    path: "/SAVES.Saves/GetUnorganizedSaves" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUnorganizedSavesRequest): Buffer =>
      Buffer.from(GetUnorganizedSavesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUnorganizedSavesRequest => GetUnorganizedSavesRequest.decode(value),
    responseSerialize: (value: GetSavesResponse): Buffer => Buffer.from(GetSavesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetSavesResponse => GetSavesResponse.decode(value),
  },
  checkSave: {
    path: "/SAVES.Saves/CheckSave" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CheckSaveRequest): Buffer => Buffer.from(CheckSaveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CheckSaveRequest => CheckSaveRequest.decode(value),
    responseSerialize: (value: CheckSaveResponse): Buffer => Buffer.from(CheckSaveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CheckSaveResponse => CheckSaveResponse.decode(value),
  },
} as const;

export interface SavesServer extends UntypedServiceImplementation {
  addSave: handleUnaryCall<AddSaveRequest, Save>;
  removeSave: handleUnaryCall<RemoveSaveRequest, RemoveSaveResponse>;
  getSavesByBoard: handleUnaryCall<GetSavesByBoardRequest, GetSavesResponse>;
  getUnorganizedSaves: handleUnaryCall<GetUnorganizedSavesRequest, GetSavesResponse>;
  checkSave: handleUnaryCall<CheckSaveRequest, CheckSaveResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
