syntax = "proto3";

package BOARDS;
option go_package = "boardspb";

// message
message Board {
  string id        = 1;
  string userId    = 2;
  string name      = 3;
  string createdAt = 4;
  string updatedAt = 5;
}

message CreateBoardRequest {
  string userId  = 1;
  string name    = 2;
  bool   private = 3;
}

message GetBoardRequest {
  string id = 1;
}

message DeleteBoardRequest{
  string id = 1;
}

message EditeBoardRequest{
  string          boardId     = 1;
  optional string boardCover  = 2;
  optional string name        = 3;
  optional string description = 4;
  optional bool   private     = 5;

}

message MergeBoardRequest{
  string mainBoardId = 1;
  string nestBoardId = 2;
}

message SuccessMessageResponse{
  bool success = 1;
}

message ListBoardsRequest {
  optional string cursor = 1;
  int32           limit  = 2;
}

message ListBoardsResponse {
  repeated Board boards   = 1;
  PageInfo       pageInfo = 2;
  message PageInfo{
    string nextCursor = 1;
    int32  limit      = 2;
  }
}

service Boards {
  rpc CreateBoard(CreateBoardRequest) returns (Board);
  rpc DeleteBoard(DeleteBoardRequest) returns (SuccessMessageResponse);
  rpc GetBoard(GetBoardRequest) returns (Board);
  rpc EditeBoard(EditeBoardRequest) returns (Board);
  rpc MergeBoard(MergeBoardRequest) returns (Board);
  rpc ListBoards(ListBoardsRequest) returns (ListBoardsResponse);

}